### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by Lanhild** [marticliment/marticliment.github.io#3]
Hello,
I am searching for a simple/free/oss solution to implement cookies on my website.

I have seen your website and would like to know what you are using for cookies?

![Screenshot_20240705_194609_Samsung Internet.png](https://github.com/marticliment/marticliment.github.io/assets/73610779/fd8275c7-6b65-44b2-8742-b231d4db6bf4)

**Comment by marticliment** [comment]
https://www.termsfeed.com/
